#ifndef CONSTANTS_H
#define CONSTANTS_H
#define MAX_VITESSE 10.0
#define AFF_SIZE 8.0
#define LIMITE_VUE 30.0

#define MILIEU_WIDTH 1000
#define MILIEU_HEIGHT 500
#define INFO_BAR_HEIGHT 220

#define INIT_BESTIOLE_NUM 40

#endif